spring:
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://allddaom-mysql.cixgstsb3mb1.ap-northeast-2.rds.amazonaws.com:3306/allddaom
    username: allddaom
    password: icandoit1!db
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10 # 3
    database-platform: org.hibernate.dialect.MySQL8Dialect
